# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cuixf/Documents/GitHub/Saturating_Inductor_Buck/Saturating_Inductor_Buck.srcs/sources_1/ip/sc_counter/sc_counter.xci
# IP: The module: 'sc_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cuixf/Documents/GitHub/Saturating_Inductor_Buck/Saturating_Inductor_Buck.srcs/sources_1/ip/sc_counter/sc_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/cuixf/Documents/GitHub/Saturating_Inductor_Buck/Saturating_Inductor_Buck.srcs/sources_1/ip/sc_counter/sc_counter.xci
# IP: The module: 'sc_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cuixf/Documents/GitHub/Saturating_Inductor_Buck/Saturating_Inductor_Buck.srcs/sources_1/ip/sc_counter/sc_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
