# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ADC_Controller_DAC/xem7010.xdc

# IP: ip/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: ip/c_addsub_2/c_addsub_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_2 || ORIG_REF_NAME==c_addsub_2} -quiet] -quiet

# IP: ip/on_time_counter/on_time_counter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==on_time_counter || ORIG_REF_NAME==on_time_counter} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
